name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate Markdown
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: "**/*.md"

      - name: Validate JSON
        run: |
          find . -name "*.json" -print0 | xargs -0 -I {} jq empty {}

      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
